---
version: '3'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=.sweetpwd.
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=.mypwd
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mysql
    links: 
       - mysql
    ports:
      - "8081:80"
  website:
    image: php:8.0-apache
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
